services:
  app:
    build:
      context: .
    container_name: wallet-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: wallet
      DB_USERNAME: user
      DB_PASSWORD: secret
    networks:
      - wallet-network

  queue:
    build:
      context: .
    container_name: wallet-queue
    working_dir: /var/www/html
    command: php artisan queue:work
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: wallet
      DB_USERNAME: user
      DB_PASSWORD: secret
    networks:
      - wallet-network

  nginx:
    image: nginx:latest
    container_name: wallet-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - wallet-network

  db:
    image: mysql:8
    container_name: wallet-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wallet
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wallet-network

volumes:
  db_data:

networks:
  wallet-network:
